version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "3000:5000" # Mapeamos el puerto 3000 del host al 5000 de Flask
    volumes:
      - ./backend/data:/app/data # ¡Regla de oro! Persistencia para la BD SQLite
      - ./backend:/app # Para hot-reload mientras desarrollas
    environment:
      - FLASK_ENV=development

  web:
    image: nginx:alpine
    ports:
      - "8080:80" # Tu frontend estará en http://localhost:8080
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - api